### ISSUE TITLE
Label this as deprecated? :-)

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/ig-article#11]

**Comment by aendra-rininsland** [comment]
@JakeChampion Possibly; I'm planning to discuss the conversation I had with @alicebartlett around the `g-` component prefix when I return to my team next week, in order to get a sense of how we're intending to use `g-ui` in the future.

That said, I don't think `g-ui` itself is depreciated at the moment, given we have some projects that still use it, and the [`jsx`](https://github.com/Financial-Times/g-ui/tree/jsx) branch contains the React components I'm hoping to eventually use to create a more streamlined version of ft-interactive/starter-kit (at which point this repo will be very active).

Closing until we decide to depreciate `g-ui`, at which point the issue will be for changing the [`supportStatus` property in `origami.json`](https://github.com/Financial-Times/g-ui/blob/master/origami.json#L6).
